export default {
  GET_API: 'GET_API',
  SIGN_UP: 'SIGN_UP',
  LOG_IN: 'LOG_IN',
  LOG_OUT: 'LOG_OUT',
  GET_USER_TOKEN: 'GET_USER_TOKEN',
  GET_TRANSACTIONS: 'GET_TRANSACTIONS',
  POST_TRANSACTION: 'POST_TRANSACTION',
  GET_TRANSACTION_BY_ID: 'GET_TRANSACTION_BY_ID',
  UPDATE_TRANSACTION: 'UPDATE_TRANSACTION',
  DELETE_TRANSACTION: 'DELETE_TRANSACTION'
};
